// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-K3YxRKK0R1JhrHXcHu1wxJTdILpvSA',
    appId: '1:163152418011:web:7fd95670d4031e9a8728fe',
    messagingSenderId: '163152418011',
    projectId: 'emailpassword-bad6a',
    authDomain: 'emailpassword-bad6a.firebaseapp.com',
    storageBucket: 'emailpassword-bad6a.appspot.com',
    measurementId: 'G-6KPJB54JG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWr-LgGwcpNqMVhTnj9gMgVeM7FTB-DAY',
    appId: '1:163152418011:android:98ef9d8ef02068e48728fe',
    messagingSenderId: '163152418011',
    projectId: 'emailpassword-bad6a',
    storageBucket: 'emailpassword-bad6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp9YpAyfUspxpok_1472EvlDcBk_wBZnQ',
    appId: '1:163152418011:ios:ff9feacc663ebc958728fe',
    messagingSenderId: '163152418011',
    projectId: 'emailpassword-bad6a',
    storageBucket: 'emailpassword-bad6a.appspot.com',
    iosBundleId: 'com.example.firebaseappemailsignupsigin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp9YpAyfUspxpok_1472EvlDcBk_wBZnQ',
    appId: '1:163152418011:ios:ff9feacc663ebc958728fe',
    messagingSenderId: '163152418011',
    projectId: 'emailpassword-bad6a',
    storageBucket: 'emailpassword-bad6a.appspot.com',
    iosBundleId: 'com.example.firebaseappemailsignupsigin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-K3YxRKK0R1JhrHXcHu1wxJTdILpvSA',
    appId: '1:163152418011:web:02994b0d4fe9f7e88728fe',
    messagingSenderId: '163152418011',
    projectId: 'emailpassword-bad6a',
    authDomain: 'emailpassword-bad6a.firebaseapp.com',
    storageBucket: 'emailpassword-bad6a.appspot.com',
    measurementId: 'G-8THJ004M0S',
  );
}
